export const REGISTERURL = 'http://localhost:8000/api/auth/users/'
export const LOGINURL = 'http://localhost:8000/api/auth/jwt/create/'
export const VERIFYTOKENURL = 'http://localhost:8000/api/auth/jwt/verify/'
export const GETUSERURL = 'http://localhost:8000/api/auth/users/me/'
export const REFRESHTOKENURL = 'http://localhost:8000/api/auth/jwt/refresh/'